---
abstract: 'efficiently pack items into rectangles'
author:
  - 'Tasuku SUENAGA a.k.a. gunyarakun <tasuku-s-cpanATATtitech.ac>'
build_requires:
  Test::Exception: 0
  Test::More: 0.98
  Test::Requires: 0
configure_requires:
  Module::Build: 0.38
dynamic_config: 1
generated_by: 'Module::Build version 0.4003, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Algorithm-BinPack-2D
no_index:
  directory:
    - inc
    - author
provides:
  Algorithm::BinPack::2D:
    file: lib/Algorithm/BinPack/2D.pm
    version: 0.01
requires:
  perl: 5.008005
resources:
  license: http://dev.perl.org/licenses/
version: 0.01
